import Head from 'next/head'
import Image from 'next/image';

import React, { useEffect, useState } from 'react'
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Home() {
  let [img, setImages] = useState(false)
  let [up, setUp] = useState(0)
  let [opt, setOpt] = useState(1)
  let [input, setInput] = useState(0)
  let page = () => {
    setImages(!img)
  }
  let updateOtp = (check) => {
    if (check == "+") {
      setOpt((+opt + 0.1).toFixed(1))
    } else {
      setOpt((+opt - 0.1).toFixed(1))
    }
  }
  let upDown = (check) => {
    if (input) {
      if (check == "up") {
        setUp(((+input) + (+up)).toFixed(1))
      } else {
        setUp(((+up) - (+input)).toFixed(1))

      }
    } else {
      if (check == "up") {
        setUp((+up + 1).toFixed(1))
      } else {
        setUp((+up - 1).toFixed(1))
      }
    }

  }
  var settings = {
    dots: true,
    infinite: true,
    speed: 500,
    // fade: true,
    autoplay: true,
    slidesToShow: 1,
    slidesToScroll: 1,
    prevArrow: <img src="/assets/images/Vector (2).png" />,
    nextArrow: <img src="/assets/images/Vector (3).png" />,
  };
  var settings2 = {
    dots: false,
    infinite: true,
    // fade: true,
    autoplay: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    cssEase: 'linear',
    autoplaySpeed: 0,
    speed: 8000,
    prevArrow: "",
    nextArrow: "",
  };
  var settings3 = {
    dots: false,
    infinite: true,
    // fade: true,
    autoplay: true,
    slidesToShow: 4,
    slidesToScroll: 1,
    cssEase: 'linear',
    autoplaySpeed: 0,
    speed: 8000,
    prevArrow: "",
    nextArrow: "",
    rtl: true
  };
  return (
    <>
      {/* <div className="checkImageFixed">
        {img && <img src="/assets/images/Landing.png" className='w-100' style={{ opacity: opt, top: `${up}px` }} alt="" />}
        <div>
          <button onClick={page}>Show {opt} {up}</button>
          <button onClick={() => updateOtp("+")}>+ </button>
          <button onClick={() => updateOtp("")}>-</button>
          <input type="text" placeholder='Enter px' onChange={(event) => setInput(event.target.value)} />
          <button onClick={() => upDown("up")}>Up</button>
          <button onClick={() => upDown("")}>down</button>
        </div>
      </div> */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='body'>
        <div className="container" >
          <div className="row ">
            <div className="col-12 col-padding-0">
              <Navbar collapseOnSelect className='navigationBarContainer' expand="lg" variant="dark">
                <Navbar.Brand href="#home">
                  <Image
                    src="/assets/images/header logo.svg"
                    alt="Picture of the author"
                    width={148}
                    height={45}
                  />
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="responsive-navbar-nav" />
                <Navbar.Collapse id="responsive-navbar-nav">
                  <Nav className="me-auto">
                    <div className='headerSearchBarContainer'>
                      <div className='pt-1'>
                        <Image
                          src="/assets/images/search.svg"
                          alt="Picture of the author"
                          width={25}
                          height={25}
                        />
                      </div>
                      <div><input type="text" placeholder='Search Collection, NFT or Seller' /></div>
                    </div>
                  </Nav>
                  <Nav className="ms-auto navigationMenu">
                    <NavDropdown title="Explore" className="me-2">

                      <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                      <NavDropdown.Divider />
                      <NavDropdown.Item href="#action/3.4">
                        Separated link
                      </NavDropdown.Item>
                    </NavDropdown>
                    <Nav.Link href="#pricing">Rewards</Nav.Link>
                    <NavDropdown title="P2P" >

                      <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                      <NavDropdown.Divider />
                      <NavDropdown.Item href="#action/3.4">
                        Separated link
                      </NavDropdown.Item>
                    </NavDropdown>
                  </Nav>
                  <Nav>
                    <button className='connectBtn'>Connect</button>
                  </Nav>
                </Navbar.Collapse>
              </Navbar>
            </div>
          </div>
        </div>
        {/* ********************************************* */}
        <div className="topBannerSection">
          <img src="assets/images/glow1.png" className='glowAnimation1' alt="" />
          <div className="container">
            <div className="row">
              <div className="col-md-6 animatedBgController">
                <div className="socialLinksContainer">
                  <a href='#' className="twitter">
                    <Image
                      src="/assets/images/tiwetter.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    />
                  </a>
                  <a href='#' className="dicoard">
                    <Image
                      src="/assets/images/discard.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    />
                  </a>
                </div>
                <div className="TopBannerWrapper">
                  <img src="assets/images/arrow.png" className='animatedSpring' alt="" />
                  <h2 className='text-white headerTitle'>Discover, collect, create &  <span>sell</span> extraordinary NFTs</h2>
                  <div className="topBannerButtonWrapper">
                    <div className="">
                      <a href="#">Explore</a>
                    </div>
                    <div className="">
                      <a href="#">Create</a>
                    </div>
                  </div>
                  <p className='totalBannerNftes'>256,000,000 NFTs</p>
                </div>
              </div>
              <div className="col-md-6 animatedBgController">
                <div className="TopBannerSlier">
                  <Slider {...settings}>
                    {[1, 1, 1, 1, 1].map((data, index) => {
                      return (
                        <div className='headerCardContainer' key={index}>
                          <div className="imageContainer">
                            <img src="/assets/images/Rectangle 1.png" alt="" />
                          </div>
                          <div className="cardHeaderContainer">
                            <div className='d-flex'><img src="/assets/images/2205194_eye_look_monitor_observe_vision_icon 1.png" alt="" className='' />(405K)</div>
                            <div className='d-flex'><img src="/assets/images/Group 817.png" alt="" className='' />0.908 ETH</div>
                          </div>
                          <div className="cardBodyContainer">
                            <h5>Project Woof</h5>
                            <p>The world’s first NFT for dogs. Created as a medium for dogs to feel human without the pressure of society</p>
                          </div>
                        </div>
                      )
                    })}
                  </Slider>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ********************************************* */}
        <div className="trendingWrapper">
          <div className="container px-30">
            <div className="row">
              <div className="col-sm-6">
                <h1 className='trendingHeading'> Trending <img src="/assets/images/fire.png" alt="" /></h1>
              </div>
              <div className="col-md-6">
                <div className="topBannerButtonWrapper mt-0 justify-content-end pe-4">
                  <div className="">
                    <a href="#">View All</a>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div className="TopBannerSlier trendingSlider w-100">
            <Slider {...settings2}>
              {[
                "Rectangle 17414.png",
                "Rectangle 17413 (1).png",
                "Rectangle 17394.png",
                "Rectangle 17411.png",
                "Rectangle 17394 (1).png",
                "Rectangle 17414.png",
                "Rectangle 17410.png",
                "Rectangle 17413 (1).png",
              ].map((data, index) => {
                return (
                  <div className='AnimatedImagesContainer' key={index}>
                    <img src={`/assets/images/${data}`} alt="" />
                  </div>
                )
              })}
            </Slider>
            <Slider {...settings3}>
              {[
                "Rectangle 17414.png",
                "Rectangle 17413 (1).png",
                "Rectangle 17394.png",
                "Rectangle 17411.png",
                "Rectangle 17394 (1).png",
                "Rectangle 17414.png",
                "Rectangle 17410.png",
                "Rectangle 17413 (1).png",
              ].map((data, index) => {
                return (
                  <div className='AnimatedImagesContainer' key={index}>
                    <img src={`/assets/images/${data}`} alt="" />
                  </div>
                )
              })}
            </Slider>
          </div>
        </div>
        {/* ********** *********************Top Collections***************************************************/}
        <div className="topBannerSection topCollectionContainer">
          <img src="assets/images/Ellipse 2.png" className='glowAnimation1' alt="" />
          <div className="container">
            <div className="row">
              <div className="col-md-7 animatedBgController">
                <h2 className='topCollectionHeading'>Top Collections</h2>
                <p className='topCollectionDes'>24hrs Volume</p>
                <div className="topCollectionListContainer">
                  {[{
                    image: "Ellipse 297.png",
                    title: "Onigiri Pepes",
                    des: "1654.45 ETH",
                    value: "12.30",
                    percentage: "  + 234234%",
                  }, {
                    image: "Ellipse 306.png",
                    title: "Mutant Ape Yatcht Club",
                    des: "4567.45 ETH",
                    value: "13.50",
                    percentage: "+ 2%",
                  }, {
                    image: "Ellipse 307.png",
                    title: "8liens NFT",
                    des: "2344.55 ETH",
                    value: "0.65",
                    percentage: " + 101.22%",
                  }, {
                    image: "Ellipse 294.png",
                    title: "Rare Apepe YC",
                    des: "34.34 ETH",
                    value: "12.30",
                    percentage: "  + 55.56%",
                  }, {
                    image: "Ellipse 295.png",
                    title: "Moodies by Hanuka",
                    des: "5432.34 ETH",
                    value: "0.40",
                    percentage: "  + 23.35%",
                  }, {
                    image: "Ellipse 296.png",
                    title: "DigiDaigaku",
                    des: "9845.22 ETH",
                    value: "1.20",
                    percentage: " + 97.89%",
                  }, {
                    image: "Ellipse 308.png",
                    title: "CLONE X- X TAKASHI...",
                    des: "123.34 ETH",
                    value: "55.55",
                    percentage: "  -45.56%",
                  }].map((data, index) => {
                    return (
                      <div key={index} className={`${index == 0 ? "mt-0" : ""} TopCollectionCard1`}>
                        <div className='flex-grow-1'>
                          <div className="imageContainer">
                            <div>
                              <img src={`/assets/images/${data.image}`} alt="" />
                            </div>
                            <div>
                              <h6>{data.title}</h6>
                              <p>{data.des}</p>
                            </div>
                          </div>
                        </div>
                        <div>
                          <div className="valueWrapper me-5">
                            <img src="/assets/images/ion_layers.png" alt="" />{data.value}
                          </div>
                        </div>
                        <div>
                          <div className="persentTageValue ">
                            {data.percentage}
                          </div>
                        </div>
                      </div>
                    )
                  })}

                </div>
                <div className="topCollectionBottomLink">
                  <button>Explore</button>
                </div>
              </div>

              <div className="col-md-5 animatedBgController">
                <h2 className='topCollectionHeading'>Top Sellers</h2>
                <p className='topCollectionDes'>Ranking</p>
                <div className="topCollectionListContainer">
                  {[{
                    image: "Avatar (8).png",
                    title: "Onigiri Pepes",
                    des: "1654.45 ETH",
                    value: "12.30",
                    percentage: "  + 234234%",
                  }, {
                    image: "Avatar (1).png",
                    title: "Onigiri Pepes",
                    des: "1654.45 ETH",
                    value: "12.30",
                    percentage: "  + 234234%",
                  }, {
                    image: "Avatar (2).png",
                    title: "Mutant Ape Yatcht Club",
                    des: "4567.45 ETH",
                    value: "13.50",
                    percentage: "+ 2%",
                  }, {
                    image: "Avatar (3).png",
                    title: "8liens NFT",
                    des: "2344.55 ETH",
                    value: "0.65",
                    percentage: " + 101.22%",
                  }, {
                    image: "Avatar (4).png",
                    title: "Rare Apepe YC",
                    des: "34.34 ETH",
                    value: "12.30",
                    percentage: "  + 55.56%",
                  }, {
                    image: "Avatar (5).png",
                    title: "Moodies by Hanuka",
                    des: "5432.34 ETH",
                    value: "0.40",
                    percentage: "  + 23.35%",
                  }, {
                    image: "Avatar (7).png",
                    title: "DigiDaigaku",
                    des: "9845.22 ETH",
                    value: "1.20",
                    percentage: " + 97.89%",
                  }].map((data, index) => {
                    return (
                      <div className={`${index == 0 ? "mt-0" : ""} TopCollectionCard1`} key={index}>
                        <div className='flex-grow-1'>
                          <div className="imageContainer">
                            <div>
                              <img src={`/assets/images/${data.image}`} alt="" />
                            </div>
                            <div>
                              <h6>{data.title}</h6>
                              <p>{data.des}</p>
                            </div>
                          </div>
                        </div>
                        <div>
                          <div className="valueWrapper me-5">
                            <img src="/assets/images/Group (2).png" alt="" />{data.value}
                          </div>
                        </div>
                        <div>
                          <div className="persentTageValue ">
                            <img src="/assets/images/Group 48095728.png" alt="" />
                          </div>
                        </div>
                      </div>
                    )
                  })}

                </div>
                <div className="topCollectionBottomLink">
                  <button>Discover</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* ********** *********************Top Collections***************************************************/}
        <div className="trendingWrapper liveAuctionContainer">
          <div className="container px-30">
            <div className="row">
              <div className="col-sm-6">
                <h1 className='trendingHeading'> Live Auctions <img src="/assets/images/fire.png" alt="" /></h1>
              </div>
              <div className="col-md-6">
                <div className="topBannerButtonWrapper mt-0 justify-content-end pe-4">

                  <div className="">
                    <a href="#">View All</a>
                  </div>
                </div>
              </div>
            </div>

          </div>
          <div className="TopBannerSlier trendingSlider w-100">
            <Slider {...settings2}>
              {[
                "Rectangle 17398.png",
                "Rectangle 17394 (2).png",
                "Rectangle 17394 (3).png",
                "Rectangle 17395 (1).png",
                "Rectangle 17396 (2).png",
                "Rectangle 17395 (2).png",
                "Rectangle 17396 (2).png",
                "Rectangle 17397 (1).png",
                "Rectangle 17397.png",
              ].map((data, index) => {
                return (
                  <div className='AnimatedImagesContainer' key={index}>
                    <img src={`/assets/images/${data}`} alt="" />
                    <div><img src="/assets/images/Group (1).png" alt="" />12:53:30</div>
                  </div>
                )
              })}
            </Slider>
            <Slider {...settings3}>
              {[
                "Rectangle 17398.png",
                "Rectangle 17394 (2).png",
                "Rectangle 17394 (3).png",
                "Rectangle 17395 (1).png",
                "Rectangle 17396 (2).png",
                "Rectangle 17395 (2).png",
                "Rectangle 17396 (2).png",
                "Rectangle 17397 (1).png",
                "Rectangle 17397.png",
              ].map((data, index) => {
                return (
                  <div className='AnimatedImagesContainer' key={index}>
                    <img src={`/assets/images/${data}`} alt="" />
                    <div><img src="/assets/images/Group (1).png" alt="" />12:53:30</div>
                  </div>
                )
              })}
            </Slider>
          </div>
        </div>
        {/* ********** *********************Top Collections***************************************************/}
        <div className="topBannerSection topCollectionContainer">
          <img src="assets/images/Ellipse 2.png" className='glowAnimation1' alt="" />
          <div className="container">
            <div className="row">
              <div className="col-md-6 animatedBgController">
                <h2 className='topCollectionHeading'>Hottest bids</h2>
              </div>
              <div className="col-md-6 animatedBgController">
                <div className="hotBidsWrapper">
                  <div className="hotBidsTabs">
                    <div className='active'>1 day</div>
                    <div>7 day</div>
                    <div>30 day</div>
                  </div>
                </div>
              </div>
            </div>
            <div className="row mt-3">
              {[{
                image: "Ellipse 297 (1).png",
                title: "CrowdSurfers",
                des: "405K",
                value: "0.508 ETH",
              }, {
                image: "Ellipse 298.png",
                title: "MKRS",
                des: "222K",
                value: "0.325 ETH",
              }, {
                image: "Ellipse 297 2.png",
                title: "Proof-of-Change",
                des: "405K",
                value: "0.908 ETH",
              }, {
                image: "Ellipse 298 (1).png",
                title: "BigFoot Town",
                des: "666K",
                value: "0.309 ETH",
              }, {
                image: "Ellipse 297 (5).png",
                title: "Reugged Revenants Club",
                des: "200K",
                value: "1.43 ETH",
              }, {
                image: "Ellipse 298 (2).png",
                title: "NFT Leaguez",
                des: "1.13M",
                value: "(1.13M)",
              },
              {
                image: "Ellipse 297 (6).png",
                title: "Lonely Listeners",
                des: "191K",
                value: "0.508 ETH",
              },
              {
                image: "Ellipse 298 (3).png",
                title: "Infinite Drive - Car Race",
                des: "5K",
                value: "(5K)",
              },
              {
                image: "Ellipse 297 (7).png",
                title: "Women of Mars",
                des: "176K",
                value: "0.45 ETH",
              },
              {
                image: "Ellipse 298 (4).png",
                title: "Wolfies",
                des: "409K",
                value: "1.234 ETH",
              },
              ].map(((data, index) => {
                return (
                  <div className="col-md-6 animatedBgController" key={index}>
                    <div className="hotBidsCardWrapper">
                      <div className='flex-grow-1'>
                        <div className="imageWrapper">
                          <div>
                            <img src={`/assets/images/${data.image}`} alt="" />
                          </div>
                          <div className="">
                            <h5>{data.title}</h5>
                            <p><img src="/assets/images/Vector (4).png" alt="" />  ({data.des})</p>
                          </div>
                        </div>
                      </div>
                      <div>
                        <div className="fireWrapper">
                          <div><img src="/assets/images/Group (3).png" alt="" /> </div>
                          <div className='ps-2'>  {data.value}</div>
                        </div>
                      </div>
                    </div>
                  </div>
                )
              }))}
            </div>
            <div className="row">
              <div className="col-12">
                <div className="exploerBtnWrapper ">
                  <button className='exploreBtn'>Explore</button>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ******************************************************** */}
        <div className="container">
          <div className="row">
            <div className="col-12">
              <h1 className='categoryTitle'>Browse by Category</h1>
            </div>
          </div>
          <div className="row categoryList">
            {[
              { imge: "Rectangle 2.png", title: "Collectibles", des: "Lost money holding shib? Project Shiba is a way to stand in solidarity with other " },
              { imge: "Rectangle 2 (1).png", title: "Art", des: "Lost money holding shib? Project Shiba is a way to stand in solidarity with other " },
              { imge: "Rectangle 2f.png", title: "Photography", des: "Lost money holding shib? Project Shiba is a way to stand in solidarity with other 1" },
            ].map((data, index) => {
              return (
                <div className="col-md-4" key={index}>
                  <div className="categoryContainer">
                    <div className="imageWrapper">
                      <img src={`/assets/images/${data.imge}`} alt="" />
                    </div>
                    <h5>{data.title}</h5>
                    <p>{data.des}</p>
                  </div>
                </div>
              )
            })}

          </div>
          <div className="row">
            <div className="col-12 allCatBtn">
              <div className="topBannerButtonWrapper mt-0 justify-content-center pe-4">
                <div className="">
                  <a href="#">All Categories</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footerContainer">
          <div className="container">
            <div className="row">
              <div className="col-md-7">
                <div className="footerLogo">
                  <Image
                    src="/assets/images/header logo.svg"
                    alt="Picture of the author"
                    width={148}
                    height={45}
                  />
                  <p>Get all the latest updates regarding NFT’s</p>
                  <div className="emailSubContainer">
                    <div className=''>
                      <input type="text" className='emailInput' />
                    </div>
                    <div>
                      <button>Subscribe</button>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-5">
                <ul className='footerLinks'>
                  <li><a href="#">Quick Links</a></li>
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Contact</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Terms of Use</a></li>
                </ul>
              </div>
            </div>
            <div className="row">
              <div className="col-12">
                <hr className='footerLine' />
              </div>
            </div>
            <div className="row">
              <div className="col-md-6">
                <p className='copyRight'>© 2022  DStage. All rights reserved</p>
              </div>
              <div className="col-md-6">
                <div className="footerSocialLinks">
                  <div><img src="/assets/images/Vector 2(5).png" alt="" /></div>
                  <div><img src="/assets/images/Group (4).png" alt="" /></div>
                  <div><img src="/assets/images/Vector (6).png" alt="" /></div>
                  <div><img src="/assets/images/Group (5).png" alt="" /></div>
                  <div><img src="/assets/images/Vector (5).png" alt="" /></div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="footerStrip"></div>


      </div>




    </>
  )
}
